### ISSUE TITLE
Supporting PETSc older versions??

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#100]
What versions of PETSc does GridPACK support and is there any reason to support PETSc version < 3.16? The develop branch is updated to use PETSc version 3.16.  There is a flag https://github.com/GridOPTICS/GridPACK/blob/46762bc961a27be805b71f6b139d0adeed355fa7/src/CMakeLists.txt#L303 that checks for older versions of PETSc.

IMHO, I don't see a reason to support older PETSc versions. Which projects are using older PETSc versions? What will it take to migrate to using develop branch?

**Comment by wperkins** [comment]
IMO, we should drop the use of [Jed Brown's FindPETSc](https://github.com/jedbrown/cmake-modules) and rely only on [pkgconfig](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html).  However, I think PETSc $\ge$ 3.12 should be supported since that's the version in Ubuntu 20 LTS (supported thru 2024).

**Comment by abhyshr** [comment]
I agree. it was Jed who suggested me to  use pkgconfig instead of FindPETSc :-) Can PETSc 3.16 not be built on Ubuntu 20 LTS? Which projects are using Ubuntu 20 LTS?

**Comment by wperkins** [comment]
Sure, you can build PETSc 3.16 on Ubuntu 20.  However, I'm thinking about ease of installation, not specific projects.  On Ubuntu, it's much easier to just install the PETSc package than to build.  In fact, on Ubuntu 20, there is no need to build any prerequisites. Just use the system packages and have GridPACK build GA.  The current GridPACK can be built with PETSc 3.12 -- 3.16 in my experience. I've not tried 3.18. 

Is there something specific in the newer PETSc that we need/want to be using?

**Comment by abhyshr** [comment]
> On Ubuntu, it's much easier to just install the PETSc package than to build.

What do you mean by this?

**Comment by wperkins** [comment]
This is all it takes: `sudo apt install petsc-dev`

**Comment by abhyshr** [comment]
Aah...I see. which version of PETSc does it install? PETSc development branch?

**Comment by abhyshr** [comment]
Can petsc-3.16 be installed? `sudo apt install petsc-3.16` or something similar?

**Comment by abhyshr** [comment]
I am thinking a little ahead here (maybe) for what PETSc version GridPACK should support for the next release. As I mentioned in the call yesterday, we should have a release early next year.

**Comment by wperkins** [comment]
> Can petsc-3.16 be installed? `sudo apt install petsc-3.16` or something similar?

No. Only 3.12 is available AFAIK. There may be PPA source, but I haven't looked.

**Comment by wperkins** [comment]
> I am thinking a little ahead here (maybe) for what PETSc version GridPACK should support for the next release. As I mentioned in the call yesterday, we should have a release early next year.

We can _support_ 3.16 and maybe even 3.18, but I would like to retain compatibility with 3.12 for a while.  I don't think this is hard to do.

**Comment by abhyshr** [comment]
Ok. It would be good to avoid using `NOT USE_OLD_PETSC` flags and other such stuff that make a distinction between which versions of PETSc are used. I think (and hope) that `pkgconfig` can handle PETSc >= 3.12 without having to resort to NOT USE_OLD_PETSC but I am not sure.

**Comment by wperkins** [comment]
Agreed. AFAIK, `USE_OLD_PETSC` only works for those versions of PETSc that produced a `PetscConfig.cmake` (or whatever) when built.  I think that stopped in 3.10 or so.

**Comment by wperkins** [comment]
If #164 is merged, 3.14.x would be the minimum PETSc version allowed.
