### ISSUE TITLE
feature/ds-dae branch

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#102]
@wperkins : https://github.com/GridOPTICS/GridPACK/tree/feature/ds-dae can this branch be deleted? I think this branch was already merged to develop branch.

**Comment by bjpalmer** [comment]
Let me check. I had an experimental branch that was looking at breaking up the evaluation of gradients in the DAE integration into small chunks so that the indexing would be easier to handle on the user side. I can't remember which branch that was in, but I'd like to hold on to those prototypes.

**Comment by wperkins** [comment]
It looks like this branch has been completely merged into `develop`. I see no reason to keep it.

**Comment by bjpalmer** [comment]
Hmm. Maybe I was hallucinating about that extra branch. I can't seem to find it. I might have just been fooling around in a local repository. At any rate, I don't have any objections to getting rid of the branch.

**Comment by abhyshr** [comment]
Closing.
