### ISSUE TITLE
where to specify PTI raw data format for power flow or contingency analysis?

### ISSUE THREAD

**Issue by diaoruisheng** [GridOPTICS/GridPACK#11]
i'd like to try running PTI V33 powerflow files. Thanks!

**Comment by diaoruisheng** [comment]
<Configuration>
  <Powerflow>
    <<networkConfiguration_v33>> IEEE14_v33.raw <</networkConfiguration_v33>>

like this?

**Comment by nie93** [comment]
I think what @bjpalmer means is change the line `<networkConfiguration> IEEE14.raw <\networkConfiguration>` to `<networkConfiguration_v33> IEEE14.raw <\networkConfiguration_v33>`. 

Is that correct?

**Comment by diaoruisheng** [comment]
I think so  :)

**Comment by chenyousu** [comment]
Yes. It is correct.

**Comment by bjpalmer** [comment]
Yes, that is what I meant.

**Comment by bjpalmer** [comment]
This is just a question of identifying the correct syntax for specifying a V33 format PSS/E file.
