### ISSUE TITLE
Replace GA-based dense matrix with native PETSc parallel dense matrix 

### ISSUE THREAD

**Issue by wperkins** [GridOPTICS/GridPACK#117]
Years ago, PETSc did not provide a parallel dense matrix and GridPACK needed one.  A PETSc add-on was written that provided a parallel dense matrix and some operations using a Global Array to store it.  Is this still appropriate? Does the PETSc parallel dense matrix provide the necessary capabilities?

**Comment by wperkins** [comment]
Related to #116.

**Comment by bjpalmer** [comment]
@abhyshr, do you know what the state of dense matrix operations is in PETSc? It used to be that PETSc was relying on the Elemental library for dense functionality, but it was impossible to build PETSc on our platforms using this option (attempts to do so inspired the famous Barry Smith comment "Guys, this is nuts"). Do you know if they have something better at this point?

**Comment by wperkins** [comment]
Well, yes, according to this: https://petsc.org/main/docs/manualpages/Mat/MATMPIDENSE. I have not looked into the details, though.

**Comment by bjpalmer** [comment]
I did a quick scan of the applications. The only modules that appear to be using Dense are some old flavors of dynamic simulation. I didn't see anything in kalman filter, but I only looked briefly. Also, my recollection is that the kalman filter does have some dense matrices, but we might be representing them (inefficiently) as sparse.

**Comment by abhyshr** [comment]
> @abhyshr, do you know what the state of dense matrix operations is in PETSc? It used to be that PETSc was relying on the Elemental library for dense functionality, but it was impossible to build PETSc on our platforms using this option (attempts to do so inspired the famous Barry Smith comment "Guys, this is nuts"). Do you know if they have something better at this point?

I don't think PETSc has anything new other than using `Elemental` or `Scalapack`. If there are no GridPACK applications using parallel dense matrix solves then I don't think we should keep supporting it in GridPACK. We can always retrieve it from a previous revision, if need be.

**Comment by wperkins** [comment]
> If there are no GridPACK applications using parallel dense matrix solves then I don't think we should keep supporting it in GridPACK.

Agreed.

**Comment by wperkins** [comment]
Done.
