### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by wperkins** [GridOPTICS/GridPACK#118]
On Linux with several PETSc versions, the following unit tests consistently fail (and been for some time):
```
The following tests FAILED:
         26 - complex_sparse_matrix_serial (Failed)
         27 - complex_sparse_matrix_parallel (Failed)
         28 - real_sparse_matrix_serial (Failed)
         29 - real_sparse_matrix_parallel (Timeout)
         52 - real_dae_solver_serial (Failed)
         53 - real_dae_solver_parallel (Failed)
         54 - petsc_ga_matrix_serial (Failed)
         55 - petsc_ga_matrix_parallel (Failed)
         79 - kalman_ds_parallel (Failed)
```
The matrix tests are failing because of PETSc matrix copy/duplicate semantics are different than when the tests were coded.   The GA matrix code (used by the kalman filter code) should probably be replaced.

**Comment by abhyshr** [comment]
GridPACK branch? PETSc version?

**Comment by wperkins** [comment]
GridPACK `develop`  and `master` branches. 
PETSc versions 3.12-3.16.  
This is not a new issue.
