### ISSUE TITLE
Can GridPACK provide a parser to output a solved powerflow file in PTI v33 format?

### ISSUE THREAD

**Issue by diaoruisheng** [GridOPTICS/GridPACK#12]
I feel it would be useful to GridPACK to output a standardized powerflow file for further applications. Any thoughts?  Thanks

**Comment by bjpalmer** [comment]
So are you thinking of writing data back out as a PSS/E v33 format file?

**Comment by diaoruisheng** [comment]
yes, that will save all the solved information

**Comment by bjpalmer** [comment]
A module for exporting PSS/E v23 and v33 are available. Closing this issue.
