### ISSUE TITLE
Cannot print vectors or matrices for any applications

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#125]
Vectors and Matrices in power flow and dynamics simulation cannot be printed out currently using the `print` method on it. `x->print(0)` does not print anything to stdout. I debugged this further and it turns out that directly calling the PETSc function `VecView` or `MatView` on the inner PETSc vector/matrix does not work either. Not sure what the issue is here. But, this is a *very important issue* that needs to be resolved as quickly as possible otherwise we cannot debug anything for the applications.

**Comment by wperkins** [comment]
@abhyshr, I know we've talked about this a bit.  Here's a copy from our conversation showing where this is happening:
```
cd build/applications/dynamic_simulation_full_y
gdb --args dsf.x input_145.xml
b dsf_app_module.cpp:3330
p INorton_full->print()
```
> It doesn't show anything for me on Mac
> On Ubuntu8, I get void
```
p INorton_full->print(0)
$1 = void
```
> On Ubuntu

**Comment by wperkins** [comment]
If you have observed this problem more generally, it would be helpful if you could outline here the environment(s)/applications  in which this is happening, e.g., OS, MPI, PETSc versions, PETSc scalar type, etc.. That is, if you have tried different environments/applications.

The `Matrix/Vector::print()` in the unit tests seem to working, for me, at least.  Have you been able to make any of those fail? Can you suggest another unit test that might expose this issue in a simpler way?

**Comment by wperkins** [comment]
Is this perhaps specific to `applications/dynamic_simulation_full_y`?

On my Ubuntu 20 machine, PETSc 3.16.6/real:
```
cd build/applications/powerflow
gdb pf.x
[...]
(gdb) info break
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x0000555555569b49 in main(int, char**) 
                                                   at /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/applications/powerflow/pf_main.cpp:26
	breakpoint already hit 1 time
2       breakpoint     keep y   0x0000155555354b9d in gridpack::powerflow::PFAppModule::solve() 
                                                   at /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/applications/modules/powerflow/pf_app_module.cpp:379
	breakpoint already hit 1 time
(gdb) run input_118.xml 
Starting program: /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/build/applications/powerflow/pf.x input_118.xml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main (argc=0, argv=0x0)
    at /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/applications/powerflow/pf_main.cpp:26
26	{
(gdb) c
Continuing.
[Detaching after fork from child process 2340410]
No protocol specified
[New Thread 0x15555186a700 (LWP 2340414)]
[New Thread 0x1555514c4700 (LWP 2340415)]

GridPACK math module configured on 1 processors

Maximum number of iterations: 50

Convergence tolerance: 0.000001
0: I have 118 buses and 179 branches
 repeat time = 1 

----------test Iteration 0, before PF solve, Tol: 9.638903e-02 

Thread 1 "pf.x" hit Breakpoint 2, gridpack::powerflow::PFAppModule::solve (
    this=0x7fffffffe310)
    at /home/d3g096/Projects/GridPACK-Wind/src/GridPACK/src/applications/modules/powerflow/pf_app_module.cpp:379
379	      solver.solve(*PQ, *X);
(gdb) p X->print(0)
Vec Object: 1 MPI processes
  type: seq
0: 0.
1: 0.
[...]
199: 0.
200: 0.
$3 = void
(gdb) 
```

**Comment by abhyshr** [comment]
Yes, it is specific to `dynamic_simulation_full_y`. I found the reason for it.

In the application driver, the noprint instance is set to true which magically suppresses printing of vectors and matrices. 
```
  gridpack::NoPrint *noprint_ins = gridpack::NoPrint::instance();
  noprint_ins->setStatus(true);
```
I have no idea what gets modified and where and how it interferes with PETSc's vector and matrix printing (Even calling `VecView` and `MatView` directly on the vector/matrix does not work!). The fix is to set `noprint_ins::status` to false. This seems to work for me. I see that the power flow appication also has something similar at the beginning but its status is set to false.

Pushing the fix in a bit.

I have no clue what the `NoPrint` class does. I have issue #126 open for discussion.

**Comment by huangrenke** [comment]
Hi Shri, Bruce and Bill, hope everything goes well with you guys. Currently I am in China and previously I could not get a good vpn (to go through the firewall in China) to access gmail and thus I am sorry I missed a lot of useful conversations here. 

The reason we need to add/set the Noprint status to be true in the dynamic_simulation_full_y is that, for the HADREC project, we simulatenously run more than 1000 instances of dynamic simulation for the reinforcement training repeatly. Before we set Noprint status to be true, the petsC will print/output a lot of matrices convergence informaiton (even if the matrices is converged) and this will mess up all the other useful messages and extremely slow down the simulation speed. So we had a discussion with Bruce, and decided to set up this Noprint status to forbidden any printout. For this point, I believe the Noprint status is a must for running a bunch of dynamic simulations in parallel for a lot of usefull applications, while for debuging and other purpose, we need to set this to be false. 

Previously when I use the dynamic simulaiton module, I typically directly use the python wrapper, and we can modify the Noprint status (True/False) in the python wrapper very easily, and I put quite detailed comments in the python wrapper for the noprint usage (https://github.com/GridOPTICS/GridPACK/blob/master/python/src/example/39bus_test_example.py,   line 51), and thus I do not pay much attention to this Noprint status issue in here. Sorry again for this. I think we may need to add some comments or other things in the README for this application to warn/avoid this issue? thanks.

**Comment by abhyshr** [comment]
Hello Renke, good to hear from you after long!! Hope you are staying safe and healthy. Thank you very much for your inputs. This helps a lot to understand what's going on. 

I haven't looked at `gridpack::NoPrint` class in detail yet, but it definitely interferes with the printing of PETSc output. Particularly, it redirects/suppresses all output from PETSc that goes to stdout. Printing the vectors/matrices to stdout is critical for debugging and we should not suppress it any cost.

PETSc **DOES NOT** print any information unless the user asks for it. I suspect there were some options set in the input xml files or some place in the GridPACK code that caused PETSc to print to sdout. 

From a software infrastructure point of view as well, `gridpack::NoPrint` is an odd-ball class that has very limited functionality. I would rather prefer to have a general "verbosity" level class that prints selective information depending on the verbosity level set. Verbosity level = 0 will print nothing and verbosity level = max_level will print all information.

This is my opinion based on looking at the GridPACK code and debugging the root cause of why PETSc vectors/matrices were not being printed. I would like to understand more about the `gridpack::NoPrint` class than what my current understanding is. I believe the `NoPrint` class has consequences for developers that can be avoided. So, I appreciate any and all additional information you may have including where all it is used. I have issue #126 open  for discussion.

**Comment by abhyshr** [comment]
FYI, I have pushed a fix (to develop branch) that resolves this issue. So I am closing this issue but feel free to comment here or in #126
