### ISSUE TITLE
powerflow.x bug report_ ubuntu ppa 

### ISSUE THREAD

**Issue by diaoruisheng** [GridOPTICS/GridPACK#13]
I was trying to run a powerflow for a small test system using the GridPACK- Ubuntu PPA version.  the results look strange, especially when checking generator terminal voltages.  Does it mean the Ubuntu PPA version don't support PTI v33 raw file?  can you please help check into this issue?
[powerflow file testing.zip](https://github.com/GridOPTICS/GridPACK/files/2338097/powerflow.file.testing.zip)

**Comment by diaoruisheng** [comment]
![image](https://user-images.githubusercontent.com/38868111/44881736-85b97b80-ac65-11e8-9b80-83ce0e6aa2cb.png)
the solved results using commercial software are attached

**Comment by bjpalmer** [comment]
We will take a look at it. It could be that the PPA package was put together before we updated the PTI 33 parser.

**Comment by diaoruisheng** [comment]
I guess so. thanks!  in the meantime, I'll try to do the full Ubuntu installation.

**Comment by wperkins** [comment]
I updated the PPA.  When I run your case on my Ubuntu 16 VM, I get
```
   Bus Number      Phase Angle      Voltage Magnitude
          1          0.000000             1.050000
          2         -4.677881             1.000000
          3        -12.964356             0.950000
          4        -10.223475             0.960410
          5         -8.552238             0.966009
          6        -14.435040             0.975000
          7        -13.774475             0.992384
          8        -13.774475             1.025000
          9        -15.647437             0.978984
         10        -15.736272             0.971266
         11        -15.235126             0.969894
         12        -15.442607             0.960674
         13        -15.592460             0.956547
         14        -16.640192             0.952464
```

**Comment by bjpalmer** [comment]
Is this the IEEE 14 bus test case? The results look a little off.

**Comment by diaoruisheng** [comment]
this is a modified IEEE14 bus test system, which is different from the original version

**Comment by bjpalmer** [comment]
Do these results look correct? Can we close this issue?

**Comment by diaoruisheng** [comment]
I believe so. thx

**Comment by bjpalmer** [comment]
Does not appear to be a problem. We are closing issue.
