### ISSUE TITLE
Move all documentation to GitHub

### ISSUE THREAD

**Issue by bjpalmer** [GridOPTICS/GridPACK#133]
The current documentation on the www.gridpack.org is expensive and is based on technology (wikimedia) that is not supported at PNNL. We should move all user documentation to GitHub. This would be more in line with current trends in documentation and would have the added benefit of relieving us of the costs of hosting the website at the lab. We should maintain the www.gridpack.org site for a year or so with a redirect link until people pick up on the new website.

**Comment by wperkins** [comment]
@bjpalmer, do you want to just move the documents [gridpack.org](https://www.gridpack.org/wiki/index.php/Main_Page) to markdown in the [Github project Wiki](https://github.com/GridOPTICS/GridPACK/wiki)? Or, do you want to move to something like [Github Pages](https://pages.github.com/) or [ReadTheDocs](https://docs.readthedocs.io/en/stable/tutorial/)?

**Comment by bjpalmer** [comment]
This task is largely completed. Documentation on building and using GridPACK has been copied to Github and is available through markdown files. We may want to do some additional restructuring in the future, but for the time being this issue is closed.
