### ISSUE TITLE
installing GridPACK on Ubuntu 16.0.4

### ISSUE THREAD

**Issue by diaoruisheng** [GridOPTICS/GridPACK#14]
I was trying to follow the instructions on the GridPACK website:
https://www.gridpack.org/wiki/index.php/Building_on_Ubuntu

the first command doesn't work 
sudo apt-get install git build-essential devscripts equivs

I have to try installing devscripts and equivs separately:
1.  sudo apt-get install devscripts
2. sudo apt-get install equivs

can you help look into this procedure and if the same problem occurs and update the GridPACK website? Thanks

Ruisheng Diao

**Comment by diaoruisheng** [comment]
found another issue when executing "make":
![image](https://user-images.githubusercontent.com/38868111/44924383-f90fcb80-acff-11e8-989d-f472423cd9a5.png)

please help check it. thanks!

**Comment by wperkins** [comment]
I cannot duplicate this on Ubuntu 16, 18 or Debian 9.  Do you get this consistently? Are you running a parallel make (`make -j`)? Could you have run out of memory?

**Comment by diaoruisheng** [comment]
I tried to repeat this process a few times and one of them went through smoothly, so this problem seems gone. thanks
