### ISSUE TITLE
Discussion: Powerflow nonlinear solver

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#144]
What is the difference between `math::RealNewtonRaphsonSolver` and `math::RealNonlinearSolver`. Why not have just one nonlinear solver as opposed to two?
@wperkins @bjpalmer

**Comment by wperkins** [comment]
`math::RealNewtonRaphsonSolver` is a basic vanilla NR solver loop using a `math::LinearSolver`.  `math::RealNonlinearSolver` is an interface to PETSc SNES non-linear solver library which is much more sophisticated. As I remember, the former is there so users don't have to figure out how to configure PETSc to do a basic NR solver.  I think there are still some GridPACK applications that have hand-coded NR loops. `math::RealNewtonRaphsonSolver`  has a simple interface that could have eliminated that extra code.

**Comment by wperkins** [comment]
I want to keep this the way it is.  Close?
