### ISSUE TITLE
Code crashes at end of some dynamic simulation runs

### ISSUE THREAD

**Issue by bjpalmer** [GridOPTICS/GridPACK#146]
The kundar 2-area test fails at the end when using the superlu_dist solver. If you replace superlu_dist with the default petsc solver the crash goes away. I've run the test through valgrind and include the output below.

[log.txt](https://github.com/GridOPTICS/GridPACK/files/10960016/log.txt)

**Comment by wperkins** [comment]
I thought I had seen this before.  [This petsc-users post](https://lists.mcs.anl.gov/pipermail/petsc-users/2021-April/043640.html) describes the same problem.  I doesn't look like it got fixed.  What PETSc version are you using?

**Comment by bjpalmer** [comment]
I'm using 3.16.3

**Comment by abhyshr** [comment]
I believe this gets fixed with #162. The issue was the dynamic simulation application was going out of scope.

**Comment by wperkins** [comment]
I too think this is fixed.
