### ISSUE TITLE
Support for different contingency types with dynamics simulation

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#152]
Currently, only a fault on/off contingency is supported by the dynamics simulation application. Extend to different types of contingency events. At minimum, we need to have
- Faults
- Line status change
- Generator status change

**Comment by huangrenke** [comment]
Hi Shri, 

line tripping and generator status changing, as well as load shedding are actually supported in the dynamic simualtion through the Hadrec module with the "action" structure. You can check the struct HADRECAction in 

src/applications/modules/hadrec/hadrec_app_module.hpp 

to see what kind of "actions" during the dynamic simulation are supported currently. and the following function is the interface for the applying the action.

void applyAction(gridpack::hadrec::HADRECAction control_action);

you can also check the python wrapper example:

python/src/example/39bus_test_example.py

lines 80 to 98, as well as 139 to 149, to see how line tripping, generator triping and load shedding can be applied during the dynamic simulation. Hope this helps.

**Comment by abhyshr** [comment]
Thanks for the note. I'll take a look at the HADREC code, but I do not intend to use it or touch if (I fear I may inadvertently break it :-)). I am making changes to the dynamic_simulation_full_y application code only. What I want to do is provide support for specifying the contingencies via the input.xml file. Currently, one can only provide a fault on a branch.

**Comment by abhyshr** [comment]
PR #162 supports setting line status and generator status through input xml file
