### ISSUE TITLE
Modify the current way a bus fault is specified in input file

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#153]
The fault is specified in the input file as a fault on a branch.
```
      <faultEvent>
        <beginFault> 1.0</beginFault>
        <endFault>   1.1</endFault>
        <faultBranch>1001 1201</faultBranch>
        <timeStep>   0.005</timeStep>
      </faultEvent>
```
This is wrong. The fault should be specified at a bus instead. This will be modified with #152

**Comment by abhyshr** [comment]
#162 uses a new format for specifying faults on buses.

**Comment by cpslab-nsu** [comment]
I beg to differ. In the real world electrical faults takes place in the lines. There is a device called Distance Relay to find the actual location of the fault within a line. Faults rarely take place at the line endpoints (buses). So, please look into this issue from that perspective.

**Comment by rahmanha** [comment]
I beg to differ. In the real world electrical faults takes place in the lines. There is a device called Distance Relay to find the actual location of the fault within a line. Faults rarely take place at the line endpoints (buses). So, please look into this issue from that perspective.

**Comment by abhyshr** [comment]
@rahmanha : Thank you for your comment! I've updated the issue title since I felt the previous one was slightly misleading.

Let me first clarify that we have **NOT** removed support for how a fault was specified. 
```
      <Events>
        <beginFault> 1.0</beginFault>
        <endFault>   1.1</endFault>
        <faultBranch>1001 1201</faultBranch>
        <timeStep>   0.005</timeStep>
      </Events>
```

However, the fault implementation in GridPACK did not actually implement a fault on a line as you describe above. It merely applied a fault at the *from* end of the line - which is same as a bus fault. For the above format, a fault will be applied on bus 1001 at t=1.0 seconds and removed at t=1.1 seconds. It **does not** apply a fault on the line at a certain length.

Since the above implementation is not a "true" line fault and is merely a bus fault, we've added a new format to specify fault on a bus which is much clearer. This will merged with the develop branch soon. Through this new format one can also specify the fault strength `yfault` (pu admittance)
```
    <Events>
      <BusFault>
        <begin> 1.0</begin>
        <end>   1.1</end>
        <bus> 1001 </bus>
        <yfault> 0.0 1000000000 </yfault>
      </BusFault>
    </Events>
```
The implementation of a fault on a line, as you describe above, will require additional work including specifying the length at which the fault is applied, including line id, fault strength, calculating the fault impedances at the two ends of the line. I am afraid this is not in scope of our current plan right now. If you could open a new issue with this feature request then that will be great! If you are interested in contributing this feature then we would certainly welcome it and provide guidance/support.

**Comment by rahmanha** [comment]
@abhyshr : Thanks a lot for your detailed answer. I can understand the scope of the present work as it is being carried out at your end. 

In my research group at North South University, we are using GridPACK as a power systems simulation engine in a Cyber-Physical System Testbed (CPS Testbed) simulator, where the data communication part is simulated through NS3. We are interested to simulate different kinds of balanced (LLL, LLLG) and unbalanced faults (LG, LL, LLG) in the transmission grid networks and their interdependencies with the data communication layer (related to wide area protection). As such, the above fault simulation capability in GridPACK is important to us. For the students in my group who are working on the power systems part, I will assign them to investigate and add these features in GridPACK. Some of them may post pull requests, or program this part themselves and post the code for merging. They may request some help from your side in this regard. Thanks in advance and best regards.

**Comment by abhyshr** [comment]
Let us know how we can help.

**Comment by abhyshr** [comment]
This feature is available with develop branch

**Comment by bjpalmer** [comment]
Then we should close this issue and delete any associated branches.
