### ISSUE TITLE
Cmake error: pkg-config tool not found

### ISSUE THREAD

**Issue by yliu250** [GridOPTICS/GridPACK#161]
By running the "install_gridpack.sh", a Cmake error may be raised saying that "pkg-config tool not found". This is because the Cmake package "pkg-config" is not installed. We can install it by typing "sudo apt-get install pkg-config", and then "source install_gridpack.sh" again to install GridPACK and Python wrapper.

**Comment by bjpalmer** [comment]
Can we add something to the script that will tell you to install it and add the instructions on how to do it?

**Comment by bjpalmer** [comment]
FindPkgConfig sets a variable PKG_CONFIG_FOUND to TRUE if the pkg-config executable is found. We could add an error message if this variable is false after calling include(FindPkgConfig) in the top-level CMakeLists.txt file.
