### ISSUE TITLE
Issue with Hadrec Env

### ISSUE THREAD

**Issue by sumathil** [GridOPTICS/GridPACK#165]
The hadrec environment used in [EXARL](https://github.com/exalearn/EXARL/tree/PARS_300bus) is returning 0s, 1s and nans for all the buses with the call `self.hadapp.getObservations()​` for 300 bus system but works for 39 bus system. This is observed for feature/init-comm branch.

**Comment by cmahrens** [comment]
Hi GridPACK team.  What do you need from the EXARL team to help track this down?  The HADREC environment prints out the following when you run the test programs for 300 bus and 39 bus systems.  We are not sure it is running correctly.  Thank you.

`This is for 300 bus system - test_gridpack_env_300bus.py file

<frozen importlib._bootstrap>:228: RuntimeWarning: mpi4py.MPI.File size changed, may indicate binary incompatibility. Expected 32 from C header, got 40 from PyObject
[(0, 0, 1.0, 0.1), (0, 1, 1.0, 0.1), (0, 2, 1.0, 0.1), (0, 3, 1.0, 0.1), (0, 4, 1.0, 0.1), (0, 5, 1.0, 0.1), (0, 6, 1.0, 0.1), (0, 7, 1.0, 0.1), (0, 8, 1.0, 0.1)]
-----------------root path of the rlgc: /pscratch/sd/s/sumathil/June_PARS/EXARL/exarl/envs/env_vault/Hadrec_dir
!!!!!!!!!-----------------start the env
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
finished loading npz file
ob_dim:  142 ac_dim:  34
finished loading the weights to the policy network
Fault tuple is  (0, 0, 1.0, 0.08)
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
-----one episode testing finished without AI-provided actions, total steps: 61 total reward:  -63786.18944549036
------------------- Episode total reward with AI provided actions:  -63786.18944549036
Fault tuple is  (0, 0, 1.0, 0.08)
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
/global/homes/s/sumathil/.local/perlmutter/3.9-anaconda-2021.11/lib/python3.9/site-packages/gym/spaces/box.py:197: UserWarning: WARN: Casting input x to numpy array.
  logger.warn("Casting input x to numpy array.")
-----one episode testing finished without any load shedding, total steps: 61 total reward:  -66293.90820762978
------------------- Episode total reward without any action:  -66293.90820762978
--------- GridPACK HADREC APP MODULE deallocated ----------
!!!!!!!!!-----------------finished gridpack env testing`

`This is for 39 bus system - test_gridpack_env_39bus.py file.

<frozen importlib._bootstrap>:228: RuntimeWarning: mpi4py.MPI.Win size changed, may indicate binary incompatibility. Expected 32 from C header, got 40 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: mpi4py.MPI.File size changed, may indicate binary incompatibility. Expected 32 from C header, got 40 from PyObject
[(0, 0, 1.0, 0.1), (0, 1, 1.0, 0.1), (0, 2, 1.0, 0.1), (0, 3, 1.0, 0.1), (0, 4, 1.0, 0.1), (0, 5, 1.0, 0.1), (0, 6, 1.0, 0.1), (0, 7, 1.0, 0.1), (0, 8, 1.0, 0.1)]
-----------------root path of the rlgc: /pscratch/sd/s/sumathil/June_PARS/EXARL/exarl/envs/env_vault/Hadrec_dir
!!!!!!!!!-----------------start the env

GridPACK math module configured on 1 processors
** PETSc DEPRECATION WARNING ** : the option -pc_factor_mat_solver_package is deprecated as of version 3.9 and will be removed in a future release. Please use the option -pc_factor_mat_solver_type instead. (Silence this warning with -options_suppress_deprecated_warnings)
** PETSc DEPRECATION WARNING ** : the option -pc_factor_mat_solver_package is deprecated as of version 3.9 and will be removed in a future release. Please use the option -pc_factor_mat_solver_type instead. (Silence this warning with -options_suppress_deprecated_warnings)
(7,)
/global/homes/s/sumathil/.local/perlmutter/3.9-anaconda-2021.11/lib/python3.9/site-packages/gym/spaces/box.py:197: UserWarning: WARN: Casting input x to numpy array.
  logger.warn("Casting input x to numpy array.")
------------------- Total steps: 50, Episode total reward without any load shedding actions:  -6436.898122330295
** PETSc DEPRECATION WARNING ** : the option -pc_factor_mat_solver_package is deprecated as of version 3.9 and will be removed in a future release. Please use the option -pc_factor_mat_solver_type instead. (Silence this warning with -options_suppress_deprecated_warnings)
------------------- Total steps: 80, Episode total reward with manually provided load shedding actions:  -2335.0126669853294
4 7 3
(51, 7) (80, 7)
(51, 4) (80, 3)
volt_ob_noact.shape:  (51, 4)
--------- GridPACK HADREC APP MODULE deallocated ----------
!!!!!!!!!-----------------finished gridpack env testing
(edited)
[2:20 PM](https://exalearn.slack.com/archives/C02JBGKQA31/p1693945226603769)
This is for 300 bus system - test_gridpack_env_300bus.py file
<frozen importlib._bootstrap>:228: RuntimeWarning: mpi4py.MPI.File size changed, may indicate binary incompatibility. Expected 32 from C header, got 40 from PyObject
[(0, 0, 1.0, 0.1), (0, 1, 1.0, 0.1), (0, 2, 1.0, 0.1), (0, 3, 1.0, 0.1), (0, 4, 1.0, 0.1), (0, 5, 1.0, 0.1), (0, 6, 1.0, 0.1), (0, 7, 1.0, 0.1), (0, 8, 1.0, 0.1)]
-----------------root path of the rlgc: /pscratch/sd/s/sumathil/June_PARS/EXARL/exarl/envs/env_vault/Hadrec_dir
!!!!!!!!!-----------------start the env
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
finished loading npz file
ob_dim:  142 ac_dim:  34
finished loading the weights to the policy network
Fault tuple is  (0, 0, 1.0, 0.08)
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
-----one episode testing finished without AI-provided actions, total steps: 61 total reward:  -63786.18944549036
------------------- Episode total reward with AI provided actions:  -63786.18944549036
Fault tuple is  (0, 0, 1.0, 0.08)
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
 in THISS cond
/global/homes/s/sumathil/.local/perlmutter/3.9-anaconda-2021.11/lib/python3.9/site-packages/gym/spaces/box.py:197: UserWarning: WARN: Casting input x to numpy array.
  logger.warn("Casting input x to numpy array.")
-----one episode testing finished without any load shedding, total steps: 61 total reward:  -66293.90820762978
------------------- Episode total reward without any action:  -66293.90820762978
--------- GridPACK HADREC APP MODULE deallocated ----------
!!!!!!!!!-----------------finished gridpack env testing`

**Comment by abhyshr** [comment]
Christine and Sumathi: sorry for the delay in replying. FY end has been busy so this issue got sidetracked. Sumathi has sent the file you are using for the 300 bus case but I have not had a chance to run it yet. Can we have a meeting to go over the error you are seeing? You can send meeting invite to shri@pnnl.gov. Next Tuesday or after would work for me.
