### ISSUE TITLE
Incorrect argument in PETSc config script

### ISSUE THREAD

**Issue by pelesh** [GridOPTICS/GridPACK#17]
There seems to be a minor error in PETSc build script on [RHEL building instructions page](https://www.gridpack.org/wiki/index.php/Building_on_RHEL). When configuring PETSc with this script following warning is returned:
```
Warning! Incorrect argument type specified: -with-fortran-kernels=generic - expecting type Bool.
```
Removing this line from the PETSc configuration does not seem to make any difference.

**Comment by pelesh** [comment]
Sorry, that would be PETSc 3.8.4.

**Comment by wperkins** [comment]
Not sure where that came from, but it's fixed.
