### ISSUE TITLE
Clean up HADREC branches

### ISSUE THREAD

**Issue by bjpalmer** [GridOPTICS/GridPACK#170]
We need to figure out which HADREC branches we can get rid of. The original HADREC code was merged into the main development branch a year or so ago, but there were a couple of major glitches when this happened and the merge did not go smoothly. It isn't clear how much of the original HADREC code survived the merge into the main branch. In addition, the code relevant to HADREC has since been modified. We may need to preserve the original HADREC branch indefinitely.

@huangrenke, do you have any strong opinions about this?

Here are the existing HADREC branches:

- [ ] feature/hadrec
- [ ] feature/hadrec-merge (del)
- [ ] feature/hadrec-rebase (del)
- [ ] feature/master-hadrec-renke

**Comment by huangrenke** [comment]
The feature/hadrec has some issues with the latest push/modification and currently is not working. 
The master branch is good and I think it has most of the features I have developed for the hadrec branch. 
For the feature/master-hadrec-renke branch, I just created it as a backup branch. 
For the feature/hadrec-merge and feature/hadrec-rebase, I have not tested them and may need a little bit more time to check it out. 
Currently I think master branch is good for hadrec and develop branch may be also OK. @bjpalmer , let me know if you need further testing or information from my side, thanks.

**Comment by abhyshr** [comment]
@huangrenke: we are going to update the main branch this quarter. The develop branch is going to replace it. So, please check if the Hadrec code is working with the develop branch. Report anything that is not working.

**Comment by abhyshr** [comment]
All hadrec related branches are deleted.
