### ISSUE TITLE
Build on RHEL 7 fails due to std::regex

### ISSUE THREAD

**Issue by pelesh** [GridOPTICS/GridPACK#18]
I tried to build GridPACK on RHEL 7 following instructions from [here](https://www.gridpack.org/wiki/index.php/Building_on_RHEL). I used mpich and Boost library from RHEL 7 packages and I built PETSc and GA following the instructions above. To configure GridPACK installation, I used following script:
```
#!/bin/bash
cmake3 -Wdev \
       -D PETSC_DIR:STRING="/usr/local/petsc" \
       -D GA_DIR:STRING="/usr/local/ga" \
       -D USE_PROGRESS_RANKS:BOOL=FALSE \
       -D MPI_CXX_COMPILER:STRING='mpicxx' \
       -D MPI_C_COMPILER:STRING='mpicc' \
       -D MPIEXEC:STRING='mpiexec' \
       -D CMAKE_INSTALL_PREFIX:PATH='/usr/local/gridpack' \
       -D CMAKE_BUILD_TYPE:STRING='RELWITHDEBINFO' \
       -D MPIEXEC_MAX_NUMPROCS:STRING="2" \
       -D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
       ../src
```
Note that I don't need to specify Boost directory, since it is already on the default path. I did, however, have to set environment variables for binary and library paths to include mpich location.

During compilation I get following error:
```
/.../gridpack/src/applications/modules/powerflow/parse_netlist.cpp: In member function ‘bool ParseNetlist::Parse(FILE*)’:
/.../gridpack/src/applications/modules/powerflow/parse_netlist.cpp:38:53: error: no matching function for call to ‘regex_replace(std::string&, std::regex&, const char [6])’
    sLineEx = std::regex_replace(sLine,rMatch,"$1_$2");
```
A little bit of googling tells me that `std::regex` does not work properly with gcc 4.8, which is default compiler on RHEL 7. This seems like a possible show-stopper for a generic RHEL 7 installation. 

One possible solution seems to be to use regex from Boost. I am not sure how much work would it be to make necessary replacements.

**Comment by wperkins** [comment]
Huh.  Can you please tell me what code revision you are working with?  I build GridPACK on RHEL7 all the time and have never run into this error.

**Comment by bjpalmer** [comment]
Where is the parse_netlist.cpp file coming from? It isn't part of the powerflow module code.

**Comment by wperkins** [comment]
I can find no mention of a file named "parse_netlist.cpp" anywhere in the history of the GridPACK git repository.

**Comment by pelesh** [comment]
Sorry guys, my bad. That was part of our GridPACK interface to Qucs, and, by the way, I fixed the problem. Function `regex_replace` required third argument to be an `std::string`, but we were passing literal `"$1_$2"`, which is `const char*`. It seems that newer versions of gcc didn't mind that, but gcc 4.8 complained. Not that this is any of your problem :).

I'll close this ticket and open a new one pertaining to other installation issues.
