### ISSUE TITLE
Change to C-shell for MacOS Installation, or update instructions for bash-shell

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#20]

**Comment by tobyjunker** [comment]
During PETSc installation, this command fails in the standard macOS bash shell:
```
setenv PETSC_DIR $HOME/gridpack/petsc-3.8.4
```
While at the top of the page use of c-shell is mentioned, this is easily overlooked and missed by the "uninitiated". Hence, I recommend to change the instructions to:
```
csh
setenv PETSC_DIR $HOME/gridpack/petsc-3.8.4
```

**Comment by wperkins** [comment]
I updated the [instruction page](https://www.gridpack.org/wiki/index.php/Building_on_Mac_High_Sierra) with both Bourne and C-shell instructions. This is consistent with the other build instructions.
