### ISSUE TITLE
Need to change directory before executing PETSc configuration

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#21]
When calling
```
./configure \
```
during the PETSc installation an error message is provided because it is not mentioned specifically to swicth to the installation directory. It is merely described to unpack the source into the gridpack directory. On that note, it may be good to mention to unpack it into a new subdirectory.

```
cd petsc-3.8.4
./configure \
```

**Comment by wperkins** [comment]
I updated the [page](https://www.gridpack.org/wiki/index.php/Building_on_Mac_High_Sierra) believe I've explicitly stated where a change directory is needed, either with some phrase like "change into" or with the actual `cd` command.  Please let me know if I've missed any.
