### ISSUE TITLE
Need developer tools for package installation on "vanilla" Ubuntu

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#22]
During the Ubuntu Installation when not needing to modify the source, i.e., when installing the binary package from the GridPACK PPA, the installation fails at this point in a vanilla Ubuntu installation:
```
cmake /usr/share/gridpack/example/powerflow
```
because a compiler cannot be found. This is remedied by first executing this command from the full installation instructions:
```
sudo apt-get install git build-essential devscripts equivs
```

**Comment by wperkins** [comment]
[Page](https://www.gridpack.org/wiki/index.php/Ubuntu_Installation) updated.
