### ISSUE TITLE
Debian -- "/etc/apt/sources.list" is read-only. sudo command not known.

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#27]
The first step in the Debian instructions is to edit */etc/apt/sources.list*. Unfortunately, the default permissions do not allow this. 

**Next problem:** I tried to change the permissions, but the default user account does not have permissions to make this change.  

**Problem number three:** I tried to make the change via *sudo*, but apparently that command is not known by default. (I did a minimal installation as seemed to have been suggested by the instructions ("Starting with a clean, minimal installation, ...")

I ended up switching into the root account via "su -". Changed permissions, then changed the file. All further steps are also done from the root account.

**Comment by pelesh** [comment]
@tobyjunker  I think it is quite dangerous to say "minimal installation" when talking about any Linux variant. In your case minimal is too minimal :). I think you need to
```
apt-get install sudo
```
with admin privileges and then add your user account to `sudoers` group. 

I think the first sentence in the instructions should say something like "For this installation you need admin/sudo privileges on your Debian box". That would make clear to users whether they can proceed on their own or they should contact their system administrator.

**Comment by pelesh** [comment]
@tobyjunker please provide hyperlink to the installation instructions to which you are referring.

**Comment by bjpalmer** [comment]
I added comments about requiring super user or sudo privileges to all builds that are using sudo, if they are not already there.

**Comment by tobyjunker** [comment]
That doesn't really address the problem. Pretty much all these instructions require sudo privileges. The problem here was that the sudo command was not known and I had to switch to the root user. 

This problem only occurred on Debian. I would think (but didn't test it) that even a minimal installation should contain the sudo command. The instructions still refer to a "clean, minim installation"

Also, to edit the sources list, I not only need sudo privileges, I also need to change the file from read only to read-write.

**Comment by wperkins** [comment]
In addition to @bjpalmer's changes,I have modified the Debian instructions as follows:

- removed "minimal" installation phrase
- specifically noted that the Debian system used was installed with the complete image, providing a link to same
- indicated how to change the permissions of `/etc/apt/sources.list`
- pointed out that `sudo` was installed automatically in this case and linked back to this ticket in case others have @tobyjunker's  problem

I don't know what else to do about this without writing a "Troubleshooting your Debian installation" page, which I won't do.

**Comment by tobyjunker** [comment]
This looks good now!
