### ISSUE TITLE
Debian Installation doesn't tell how to obtain source code

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#29]
The following instructions, taken from the Ubuntu from scratch installation are missing in the Debian instructions:
```
git clone https://github.com/GridOPTICS/GridPACK.git
cd GridPACK
git submodule update --init
```
Also, change of the directory needs to be included:
```
mkdir src/build
cd src/build
```

**Comment by bjpalmer** [comment]
I added text to describe how to download the GridPACK tarball, make the build directory and cd into it. I'd rather people go download the tarball than clone the github repository.
