### ISSUE TITLE
Results changed when branch orientation reversed

### ISSUE THREAD

**Issue by pelesh** [GridOPTICS/GridPACK#30]
When changing orientation of a power flow branch model, the results for active and reactive power change, as well. Take, for example, contingency analysis for IEEE 14-bus example and change orientation of the branch between buses 1 and 5. with one orientation the output file `CTG2.out` shows power flow through the branch to be:
```
        Bus 1       Bus 2   CKT         P                    Q
         ...
          1           5     BL      82.504609             3.345018
```
When connecting the same branch model in the opposite direction, the results should not change except for the power flow direction. Yet, the magnitude of active and reactive power flows do change in this case:
```
        Bus 1       Bus 2   CKT         P                    Q
         ...
          5           1     BL     -79.213409             4.920635
```
This seems to be violating the physics -- the transmission line should have the same power flow properties in both directions.

**Comment by bjpalmer** [comment]
This is basically the same as issue #10. This was partially addressed by Yousu, but I don't know if he fully put it to bed.

**Comment by pelesh** [comment]
Duplicate of #10

**Comment by bjpalmer** [comment]
I think this is a non-issue (based on the response to 10). I'm going to close it. It might be worth considering whether to include flows in both directions in the output.

**Comment by bjpalmer** [comment]
Closed
