### ISSUE TITLE
DAE Solver Tests caught in infinite loop with PETSc 3.8

### ISSUE THREAD

**Issue by wperkins** [GridOPTICS/GridPACK#32]
I've experienced this on many platforms with PETSc 3.8.  All of the DAE solver tests, both serial and parallell, will time out.  The tests call `DAESolverT<>::solve()` repeatedly expecting the time integration to continue where it left off.  This has worked with previous PETSc versions, but with 3.8, the second solve simply returns without advancing the solution.

**Comment by pelesh** [comment]
I think these are the offending lines: In file `petsc_dae_solver_implementation.hpp` in function `p_solve` it is set
```c++
      ...
      PetscInt nstep;
      ierr = TSGetStepNumber(p_ts,&nstep);CHKERRXX(ierr);
      maxsteps = nstep; // <~ commentthis out
      ...
      PetscReal tlast;
      ierr = TSGetSolveTime(p_ts,&tlast);CHKERRXX(ierr);
      maxtime = tlast; // <~ comment this out
      ...
```
In the unit test there is a loop
```c++
    for (int i = 1; t < p_maxtime; ++i) 
    {
      t = t0 + p_outstep*i;
      solver.solve(t, p_maxsteps);
      std::cout << "i = " << i << ", Time = " << t << std::endl;
      x->print();
    }
```
At the next iteration, `t` will be reset to the time of the first iteration thus not meeting the for-loop exit condition, and `p_maxsteps` will be set to the number of steps from the first iteration thus never getting to the time `t = t0 + p_outstep*i`.

Commenting out offending lines and setting `p_solve` output to
```c++
        std::cout << this->processor_rank() << ": "
                  << "PETSc DAE Solver converged after " << nstep << " steps, "
                  << "actual time = " << tlast
                  << std::endl;
```
will fix this issue.
