### ISSUE TITLE
CentOS 6 Install - Missing Boost Link (& GlobalArrays duplicate link)

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#34]
the link to Install Boost is missing on this page:
https://www.gridpack.org/wiki/index.php/Building_on_CentOS6

I looked for the link on the general install from scratch page, and while there is a link, it points to the wrong location:
https://www.gridpack.org/wiki/index.php/How_to_Build_GridPACK

The Boost link points to the PNL location for GlobalArrays whereas the other GlobalArrays link points to GitHub. Which link is correct?

**Comment by tobyjunker** [comment]
I googled boost 1.54 and also the latest Global Arrays. Install went fine. Please fix links.

**Comment by bjpalmer** [comment]
I think these are fixed. Can you (Toby) verify and close this issue?
