### ISSUE TITLE
CentOS 6 -- Missing link to PETSc 3.6.4

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#36]
The "How to build GridPACK from scratch" page (https://www.gridpack.org/wiki/index.php/How_to_Build_GridPACK) contains a link for PETSc, yet no version 3.6.4 can be found there. Versions on the SVN repository only go back to 4.3.  By the way, that servers security certificate expired on September 29. I had to override the certificate in firefox to go to the repository. I was hoping to find version 3.6 -- but I didn't.

I found the version on this page:
https://www.mcs.anl.gov/petsc/download/index.html
(security certificate also out of date)

**Comment by diaoruisheng** [comment]
sometimes, the PETSC link got changed by ANL guys. a simple google search would fix the problem.

**Comment by wperkins** [comment]
I put a link to the [PETSc](url) download page in the [PETSc section](https://www.gridpack.org/wiki/index.php/Building_on_CentOS6#PETSc.2C_version_3.6.4) of the [CentOS 6 build](https://www.gridpack.org/wiki/index.php/Building_on_CentOS6) page.

**Comment by tobyjunker** [comment]
Yes. Thank you.
