### ISSUE TITLE
Combine instructions for Red Hat/CentOS.  Provide separate instructions for Version 6 vs. Version 7

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#38]
Per suggestion from Slaven, rather than listing CentOS 6 and Red Hat Enterprise Linux as two separate instruction sets, it would make more sense to treat these two together and instead give instructions for:

* Red Hat Enterprise Linux/ CentOS Version 6.x
* Red Hat Enterprise Linux/ CentOS Version 7.x.

With some trouble (see tickets [#34](https://github.com/GridOPTICS/GridPACK/issues/34) & [#36](https://github.com/GridOPTICS/GridPACK/issues/36) ) I got [CentOS 6.10](https://github.com/GridOPTICS/GridPACK/issues/37) to work with many failed tests, but [CentOS 7](https://github.com/GridOPTICS/GridPACK/issues/35) failed during the first step.

**Comment by diaoruisheng** [comment]
I installed CENTOS 7 without much trouble.  only two tests failed out of 81. you might want to try a few times when compiling GridPACK. but before that, you will need to SUCCESSFULLY install BOOST, PETSC and GA.   especially when installing PETSC, the last few steps would need manual operation, required by the PETSC installation. You will have to copy and paste the last commands and hit enter, to install PETSC. the last step, to compile GridPACK, is relatively straightforward, but sometimes, it throws out errors, mostly with PETSC. the second, or 3rd try would run through.

**Comment by wperkins** [comment]
@tobyjunker, I put together some [instructions](https://www.gridpack.org/wiki/index.php/Building_on_CentOS7) for CentOS/RHEL 7.  All unit tests pass on my VM.
