### ISSUE TITLE
Ubuntu from Scratch -- Explain how to fix timeout unit tests

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#40]
Continuation of Issue #24. Instructions need to be updated to mention time out errors and what to do about them.

**Comment by diaoruisheng** [comment]
what does this mean?  I don't think it's an issue preventing you from running some grid simulations

**Comment by wperkins** [comment]
See [here.](https://www.gridpack.org/wiki/index.php/How_to_Build_GridPACK#Running_Tests)
