### ISSUE TITLE
Ubuntu from Scratch -- Kalman Filter Unit Test fails

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#41]
Continuation of Issue #24. Instructions need to be updated to mention this error. Ultimately it needs to be fixed. 

I will now test the suggestion from [this comment](https://github.com/GridOPTICS/GridPACK/issues/24#issuecomment-426831413) to run the test individually.

**Comment by wperkins** [comment]
I see this happen on a number of platforms I work with.  I think it's a bug and have started an issue (#52) to deal with it.  IMHO, we shouldn't need to modify the [gridpack.org](https://www.gridpack.org/wiki/index.php/Main_Page) documentation every time a particular bug pops up.

**Comment by tobyjunker** [comment]
Since you now have a designated Section on Unit Tests, it would be easy enough to add a link to issue #52. Presently, it seems there is three types of failed unit tests. Timeout and regular expression are specifically being mentioned. This one should too, then.

**Comment by wperkins** [comment]
I would _really_ like to avoid documenting every bug in two places.  I added the following to the Unit Tests section:

    If a test fails, it possible that a bug report has been made. Check [https://github.com/GridOPTICS/GridPACK/issues here][[current issues] to see. 

And a little farther down:

    If you wish to report a bug about a failed unit test, run the test as described and post it with the bug report.  

Would that work?
