### ISSUE TITLE
Ubuntu from Scratch -- Add Powerflow example

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#43]
Broken out sub-issue from #26. After installing Ubuntu from scratch, a unit test is run, but no application example is given. The example given in the Ubuntu Package install should be included here as well.

**Comment by diaoruisheng** [comment]
powerflow examples are included after you install GridPACK on Ubuntu, did you miss any steps?

**Comment by wperkins** [comment]
I repeated what I did for #48 on the [Ubuntu](https://www.gridpack.org/wiki/index.php/Building_on_Ubuntu#Build_and_Test_GridPACK) build page.
