### ISSUE TITLE
Ubuntu from Package -- Add Unit tests

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#44]
Broken out sub-issue from #26. After installing Ubuntu from a package, an application example is run, but no unit tests are performed. The unit test run after the Ubuntu Package from scratch install should be included here as well.

**Comment by diaoruisheng** [comment]
I tried the Ubuntu 16.0.4 version and didn't find any issues when using GridPACK for performing different types of power grid simulations

**Comment by wperkins** [comment]
The unit tests cannot be run from the installed binary package, only from source.  While several example applications (like powerflow) are installed with the binary package,  most of the unit tests have no value except to those messing with the GridPACK source.

**Comment by tobyjunker** [comment]
Thank you for the clarification.
