### ISSUE TITLE
CentOS 6 -- Add Powerflow example

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#45]
Broken out sub-issue from #26. After installing CentOS 6 from scratch, a unit test is run, but no application example is given. The example given in the Ubuntu Package install should be included here as well.

**Comment by diaoruisheng** [comment]
see my comments in your other issue

**Comment by wperkins** [comment]
I repeated what I did for #48 for the [CentOS 6](https://www.gridpack.org/wiki/index.php/Building_on_CentOS6#GridPACK) page.
