### ISSUE TITLE
CentOS 7 -- Add Powerflow example

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#46]
Broken out sub-issue from #26. After installing CentOS 7 from scratch, a unit test is run, but no application example is given. The example given in the Ubuntu Package install should be included here as well.

**Comment by diaoruisheng** [comment]
I installed Centos7 version and can see examples in the src/build_yours/application/powerflow folder. it comes with a couple of test systems. Did you miss any steps when installing GridPACK3.2???
