### ISSUE TITLE
Debian -- Add Powerflow example

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#47]
Broken out sub-issue from #26. After installing Debian from scratch, a unit test is run, but no application example is given. The example given in the Ubuntu Package install should be included here as well.

**Comment by wperkins** [comment]
I repeated what I did for #48 for the [Debian](https://www.gridpack.org/wiki/index.php/Building_on_Debian#GridPACK_Configuration_and_Build) build page.
