### ISSUE TITLE
Explain how to alleviate timeout errors on Red Hat installation.

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#49]
The [Red Hat Installation](https://www.gridpack.org/wiki/index.php/Building_on_RHEL) makes this statement at the end:

`This will run numerous module and application tests within GridPACK. Some tests may fail. If you see errors due to timeouts or failure to match regular expressions, these are usually harmless.
`

This is not satisfactory. Since timeout errors are easy to fix, please explain how to do so.

**Comment by bjpalmer** [comment]
Done.
