### ISSUE TITLE
Red Hat -- Fix regular expression error in unit test

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#50]
The [Red Hat Installation](https://www.gridpack.org/wiki/index.php/Building_on_RHEL) makes this statement at the end:

`This will run numerous module and application tests within GridPACK. Some tests may fail. If you see errors due to timeouts or failure to match regular expressions, these are usually harmless.
`

This is not satisfactory. Regular expression errors should be able to be fixed by installation a Boost Reg Ex package as [described here](https://github.com/GridOPTICS/GridPACK/issues/37#issuecomment-427420868).

**Comment by wperkins** [comment]
Please refer to my comments in #37 about "regular expression errors". 
Have you tried the fix you recommend?  Did the installation of Boost Reg Ex  package  fix the problem for you? Please let us know exactly what you did to fix this. Thanks.

**Comment by tobyjunker** [comment]
I did not install the Boost Reg Ex package. This wasn't a fix I wanted to try, but rather a suggested fix for you to get rid of all these reg ex errors. In a separate e-mail conversation I found out that you too have these errors, hence there seems to be a bigger issue than merely my own installation.
