### ISSUE TITLE
Debian -- Timeout errors during Unit Tests

### ISSUE THREAD

**Issue by tobyjunker** [GridOPTICS/GridPACK#51]
In Issue #28, comments for the Debian installation were added with regard to timeout and regular expression errors. Timeout errors can be fixed by extending the time limit. Please explain how to do this.

**Comment by wperkins** [comment]
@tobyjunker,  I added a [lengthy section](https://www.gridpack.org/wiki/index.php/How_to_Build_GridPACK#Running_Tests) on running GridPACK unit tests and some hints on what to do if some fail.  See if it's understandable.  Thanks.

**Comment by tobyjunker** [comment]
Thank you. Good idea to add this description as a separate section.

Note that the obviously ironic statement: "Note that, in this example, two tests were reported as failed and the reason was very helpfully reported as Failed." may be missed by some and should be reformulated to state clearly that it is no helpful.

The discussion about timeouts is fine.

You explain how to run a separate test that passes. This is useful.

The discussion about regular expression not so much. In a separate issue (I don't remember which one), you pointed out that a regular expression test failed as part of the unit test, but passed if run individually. This example should be included here. Explain how I can run a failed test individually and how I can tell if it actually failed or was only falsely reported as having failed.
