### ISSUE TITLE
Using deprecated PETSc functions

### ISSUE THREAD

**Issue by pelesh** [GridOPTICS/GridPACK#53]
Implementation of PETSc DAE solver driver in file `petsc_dae_solver_implementation` uses deprecated PETSc functions `TSSetInitialTimeStep` and `TSGetTimeStepNumber`. 

[PETSc documentation](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/TS/) suggests using `TSSetTime` and `TSSetTimeStep` instead of `TSSetInitialTimeStep`, and `TSGetStepNumber` instead of `TSGetTimeStepNumber`.

Please consider updating for future compatibility.

**Comment by wperkins** [comment]
It looks like these were deprecated in some time in 3.8.x.  I'm going to wait awhile because compatibility with 3.6 and 3.7 is important.

**Comment by wperkins** [comment]
It looks like this got fixed quite some time ago. Closing ...
