### ISSUE TITLE
PETScConfig.cmake missing?

### ISSUE THREAD

**Issue by python152** [GridOPTICS/GridPACK#79]
hi -

My install failed at PETSc, particular with the PETScConfig.cmake not found. I tried both `spack install petsc` as well as from the source directly, and I don't see this .cmake anywhere. Did I miss anything?

thanks

```
message(STATUS "Using PETSc version ${PETSC_VERSION}")

if (EXISTS "${PETSC_DIR}/${PETSC_ARCH}/conf/PETScConfig.cmake")
  include("${PETSC_DIR}/${PETSC_ARCH}/conf/PETScConfig.cmake")
elseif (EXISTS "${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/PETScConfig.cmake")
  include("${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/PETScConfig.cmake")
elseif (EXISTS "${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/PETScBuildInternal.cmake")
  include("${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/PETScBuildInternal.cmake")
```

**Comment by bjpalmer** [comment]
Hi,

It looks like you downloaded GridPACK directly from the github repository. If you do this (instead of using the release tarball), you need to run

git submodule update --init

in the top level directory to pick up some additional files. The PETSc confuration should then work.

Bruce

**Comment by python152** [comment]
hi - thanks for the reply. but I have done the submodule update step, that is not the issue, I think. 
There seems to be either `PETScConfig.cmake` or `PETScBuildInternal.cmake` generated by either PETSc or GridPack, but I can't find it anywhere. Nonetheless, GridPack cmake does expect this ...

**Comment by abhyshr** [comment]
Which PETSc version are you using? I don’t think GridPack is compatible with the latest PETSc release or master. The one that I know works is PETSc 3.8.

Shri

On Aug 23, 2020, at 1:15 PM, python152 <notifications@github.com> wrote:

﻿

hi - thanks for the reply. but I have done the submodule update step, that is not the issue, I think.
There seems to be either PETScConfig.cmake or PETScBuildInternal.cmake generated by either PETSc or GridPack, but I can't find it anywhere. Nonetheless, GridPack cmake does expect this ...

**Comment by bjpalmer** [comment]
If there is a FindPETSc.cmake file under $GRIDPACK/cmake-jedbrown, then you should be good as far as the submodule update is concerned. Based on the CMake code that you showed above, it looks like PETSc keeps shifting the name and location of of the PETScConfig.cmake code so Shri's question may be applicable. For 3.7.7, the last option is the one that works. For 3.6.0 it is the second option. I think the last option also works for 3.8, 3.9 and 3.10. I don't believe anyone has tested 3.11 but a quick look suggests that the third option should work for that as well.

**Comment by wperkins** [comment]
PETScConfig.cmake is generated by PETSc when it's built. The GridPACK CMake configuration currently depends on the contents of PETScConfig.cmake to determine if the PETSc build is appropriate.  
However, PETSc stopped generating PETScConfig.cmake with version 3.11 or 3.12 and GridPACK has not yet adapted to that.
Try PETSc 3.8 to 3.10.

**Comment by python152** [comment]
thank you all, you guys are spot on, neither 3.11 nor 3.12 work. Moving down to 3.10 solved this particular problem!
