### ISSUE TITLE
how to specify PTI33_parser in input.xml

### ISSUE THREAD

**Issue by yhwu** [GridOPTICS/GridPACK#80]
Hello, I have a PSSE 30  raw file. How do I use the PTI33_parser in input.xml to read it in? Thanks!

**Comment by chenyousu** [comment]
The current GridPACK only supports PTI23 and PTI33 format. You will need to use a commercial tool, such as PSLF/PSSE/Powerworld to convert the model in PTI33 or PET23 in advance.

**Comment by yhwu** [comment]
So, if I want to run power flow for 118_PTIv33.raw which is in V33 format, how do I tell the program to use V33? Can it be done in the xml configuration or do I need to make changes in the source code?

<Configuration>
  <Powerflow>
    
    <networkConfiguration> 118_PTIv33.raw </networkConfiguration>	
......
  </Powerflow>
</Configuration>

Network filename: (118_PTIv33.raw)
Using V23 parser
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range

**Comment by yhwu** [comment]
Ok, got it. Just use <networkConfiguration_v33> 118_PTIv33.raw </networkConfiguration_v33>
