### ISSUE TITLE
[Help wanted] A question about dynamic simulation with dynamic load on specific bus

### ISSUE THREAD

**Issue by lzheng28** [GridOPTICS/GridPACK#84]
I want to use the dynamic simulation module in [GridPACK dynamic simulation with full Y matrix](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp), and I think the loads of each bus is read by the PTIv23/PTIv33 files and are static, but in actually power system, the loads of buses may change during this process (for example, there is one specific bus connected to the distribution system, and the distribution system loads change in each time step), so I prepare to change the load of one specific bus in the network in each simulation time step, but when I change the load in each time step, the simulation result (Generators' speed and angle) does not change. 

At present, I think if I change the load, it will influence the Y matrix during the computation in solve function, that is, I need to reset the Y bus, so I tried to change the load first in the [for loop](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L506) and then use ```p_factory->setYBus();``` to reset Y bus of the network, but the Y bus doesn't change. Could you please give me any hint or instruction about how to do that or do I need to reset other variable after I change the loads? Thank you so much!

**Comment by bjpalmer** [comment]
I don't think the Y-bus has any explicit dependence on the loads. Have you tried the setLoad function? Although the parameters set by the setLoad function appear to be functions of other parameters. See the DSFFullBus::load function.

**Comment by lzheng28** [comment]
> I don't think the Y-bus has any explicit dependence on the loads. Have you tried the setLoad function? Although the parameters set by the setLoad function appear to be functions of other parameters. See the DSFFullBus::load function.

Yes, I've tried this method in the [for loop](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L506) like
```
gridpack::dynamic_simulation::DSFullBus *dsbus = dynamic_cast<gridpack::dynamic_simulation::DSFullBus*>(p_network->getBus(6).get());
dsbus->setLoad(1.3, 1.3);
```
but the result (watched generator angle and speed) doesn't change.
And I even revised the load and datacollection of the specific bus, like
```
gridpack::component::DataCollection *dsData;
dsData = p_network->getBusData(6).get();
double temp;
dsData->setValue(LOAD_PL, 130);
dsData->setValue(LOAD_QL, 130);
```
But the result still not changed.

And I also tried to revised the Load in the [dsf_main.cpp](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/dynamic_simulation_full_y/dsf_main.cpp#L111) after the  pf_network is initialized and after the ds_network is initialized (actually I need to use setLoad() function and revised the datacollection in the same time). And the result will change. This method can only changed the Load before the [for loop](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L506)

But I want to change the Load in the [for loop](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L506) in each time step. This can't be done by setLoad() and revised datacollection so far.

**Comment by bjpalmer** [comment]
I will try and find somebody that is more knowledgeable about this than I am to help you. It may be that you need to  call a mapper or something to propagate your changes to the appropriate matrices. Changing the datacollection objects will only affect the result if you do it before calling the p_factory->load method (or the load method on individual buses).

**Comment by lzheng28** [comment]
And I also tried the ```DSFullApp::reload()``` function, but when I call it in the for loop, the [INorton_full](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L551) will be have ```nan``` value which will lead to error in the [solve stage](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L575)

**Comment by bjpalmer** [comment]
My guess is that after you modify the load parameters, you need to call mapToMatrix using one of the mappers defined in the section before the time loop. I'm not a power grid engineer, so I couldn't tell you which one it is for sure, but if I had to take a guess I would suggest `ybusyl`. This will update the matrix based on the new parameters . From what I can see, the existing codes assumes that all matrices constant during the simulation and only the right hand sides need to be updated as the simulation proceeds.

**Comment by lzheng28** [comment]
I'm sorry, do you mean that I need to use the [two lines](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L289-L290) to update the matrix after I change the datacollection of bus and use the ```DSFullApp::reload()``` in each time step? I'm not sure how to use ```ybusyl``` to call ```mapToMatrix()```, so I just use this [two lines](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L289-L290) after I call ```DSFullApp::reload()```, but it still failed because ```INorton_full``` still has ```nan``` values. 

And actually, I want to update the Load in the time loop because I assume the Load of the specific bus is changing during the whole simulation period, so "call it before the time loop" may have conflict with what I need.

**Comment by bjpalmer** [comment]
Oops, I misspoke on how to update the matrix. `ybusyl` is the matrix, `ybusMap` is the corresponding mapper. I would skip the call to reload and just call `ybusMap.mapToMatrix(ybusyl)` after modifying the loads on the buses.

**Comment by lzheng28** [comment]
I add the codes [here](https://github.com/GridOPTICS/GridPACK/blob/master/src/applications/modules/dynamic_simulation_full_y/dsf_app_module.cpp#L653) ( and the input is input_9b3g.xml, I want to change the 7th node Load)
```
    gridpack::dynamic_simulation::DSFullBus *dsbus = dynamic_cast<gridpack::dynamic_simulation::DSFullBus*>(p_network->getBus(6).get());
    dsbus->p_pl = 1.30;
    dsbus->p_ql = 1.30;

    gridpack::component::DataCollection *dsData;
    dsData = p_network->getBusData(6).get();
    double temp;
    dsData->getValue(LOAD_PL, &temp); std::cout << "LOAD_PL: " << temp << std::endl; //it printed 100 in all time steps
    dsData->setValue(LOAD_PL, 130);
    dsData->getValue(LOAD_QL, &temp); std::cout << "LOAD_QL: " << temp << std::endl; //it printed 35 in all time steps
    dsData->setValue(LOAD_QL, 130);

    ybusMap.mapToMatrix(ybusyl);
```
But the result still didn't change.

**Comment by huangrenke** [comment]
Changing bus load values during dynamic simulation is much more complicated than just modifying the LOAD_PL and LOAD_QL values, you need to modify the system Y-matrix accordingly with respect to the changed LOAD_PL and LOAD_QL, or modify the injection currents of the bus accordingly. 

We have already provided this functionality of changing load values during dynamic simulation through python wrapper. I guess you are trying to run co-simulation together with GridLABD? Try the python wrapper to run a dynamic simulation and you can also add HELICS time synchronization in the python code, which provides you the flexibility of getting rid of HELICS in GridPACK C++ code.

To use the python wrapper of the GridPACK, switch to the 'feature/hadrec' branch, compile GridPACK, and then cd to the 'python folder' under the root directory of the GridPACK repo, follow the README instructions to install the GridPACK python wrapper to your python. There are two python examples under /gridpack_repo/python/src/tests directory you can take a look. "39bus_test_example.py" shows how to run dynamic simulation with python, "39bus_scatterload_steptest_new_itr.py" shows how to change loads during the dynamic simulation.

**Comment by lzheng28** [comment]
Thank you so much, I tried to install GridPACK with python, but when I ran the ```python setup.py test```, it will have an error as the following.
```
(helics-example) lei@lei-VirtualBox:~/Install_package/GridPACK-renke/python$ python setup.py build
running build
running build_ext
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /home/lei/anaconda3/envs/helics-example/bin/python (found version "3.7.10") 
-- Found PythonLibs: /home/lei/anaconda3/envs/helics-example/lib/libpython3.7m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.4.3
statusGRIDPACK_HAVE_GOSS: OFF
statusGRIDPACK_GOSS_LIBRARY: 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lei/Install_package/GridPACK-renke/python/build/temp.linux-x86_64-3.7
Scanning dependencies of target parallel_scripts
[  0%] Built target parallel_scripts
Scanning dependencies of target gridpack
[ 50%] Building CXX object src/CMakeFiles/gridpack.dir/gridpack.cpp.o
[100%] Linking CXX shared module ../../lib.linux-x86_64-3.7/gridpack.cpython-37m-x86_64-linux-gnu.so
[100%] Built target gridpack
running build_scripts
creating build/scripts-3.7
copying and adjusting src/hadrec.py -> build/scripts-3.7
changing mode of build/scripts-3.7/hadrec.py from 664 to 775
(helics-example) lei@lei-VirtualBox:~/Install_package/GridPACK-renke/python$ python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
creating gridpack_hadrec.egg-info
writing gridpack_hadrec.egg-info/PKG-INFO
writing dependency_links to gridpack_hadrec.egg-info/dependency_links.txt
writing top-level names to gridpack_hadrec.egg-info/top_level.txt
writing manifest file 'gridpack_hadrec.egg-info/SOURCES.txt'
reading manifest file 'gridpack_hadrec.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'gridpack_hadrec.egg-info/SOURCES.txt'
running build_ext
-- pybind11 v2.4.3
statusGRIDPACK_HAVE_GOSS: OFF
statusGRIDPACK_GOSS_LIBRARY: 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lei/Install_package/GridPACK-renke/python/build/temp.linux-x86_64-3.7
[  0%] Built target parallel_scripts
[ 50%] Linking CXX shared module ../../../gridpack.cpython-37m-x86_64-linux-gnu.so
[100%] Built target gridpack

GridPACK math module configured on 1 processors
MA error: MA_init: MA already initialized

Maximum number of iterations: 20

Convergence tolerance: 0.000000
0: I have 43 buses and 50 branches
 repeat time = 1 

----------test Iteration 0, before PF solve, Tol: 1.566006e+01 

Iteration 1 Tol: 2.147061e+00

Iteration 2 Tol: 1.440133e-01

Iteration 3 Tol: 4.942355e-04

Iteration 4 Tol: 4.797769e-09

   Branch Power Flow

        Bus 1       Bus 2   CKT         P                    Q
          1           2     1     -103.331006           -19.822909
          1          39     1      103.331006            19.822909
          2           3     1      375.616244           152.442788
          2          25     1     -229.300083            66.388648
          3           4     1       10.502623           120.768420
          3          18     1       41.093980            33.031880
          4           5     1     -223.246391            11.372399
          4          14     1     -266.472870           -64.898241
          5           6     1     -543.854468           -79.641213
          5           8     1      320.196153            97.494856
          6           7     1      439.208608           140.567998
          6          11     1     -309.167341           -77.568796
          7           8     1      204.097406            14.613890
          8           9     1        1.184655          -140.357327
          9          39     1        0.821023          -108.348706
         10          11     1      315.183440           111.567531
         10          13     1      334.816560            49.946619
         13          14     1      331.647124             4.438299
         14          15     1       63.574045           -50.605142
         15          16     1     -256.518091          -168.089973
         16          17     1      290.351871            11.389865
         16          19     1     -504.967550           -77.803264
         16          21     1     -329.473578           -11.093905
         16          24     1      -42.644481          -113.884061
         17          18     1      280.731697            82.654466
         17          27     1        9.051629           -64.552820
         21          22     1     -604.306934          -113.519524
         22          23     1       42.830882            43.402884
         23          24     1      353.857251            17.677078
         25          26     1       81.296410            -8.326890
         26          27     1      273.081099            92.820746
         26          28     1     -140.910575           -30.115157
         26          29     1     -190.076898           -33.770366
         28          29     1     -347.700706            18.708634
          2          30     1     -250.000000          -166.676061
          4         504     1      500.000000           192.844258
          6          31     1     -674.515431          -146.455430
          7         507     1      233.800000           116.756422
          8         508     1      522.000000           258.957689
         10          32     1     -650.000000          -161.514150
         12          11     1       -4.823068           -41.059496
         12          13     1       -2.676932           -46.940504
         18         518     1      163.200000           113.767012
         19          20     1      120.104889           -11.703215
         19          33     1     -629.046345           -82.093989
         20          34     1     -508.000000          -116.771026
         22          35     1     -650.000000          -179.537574
         23          36     1     -558.552138           -39.200861
         25          37     1     -538.340143            38.923590
         29          38     1     -824.756025            59.848873

   Generator Power

   Bus Number  GenID        Pgen              Qgen
         30      1        2.500000          1.824787
         31      1        6.837154          2.901442
         32      1        6.500000          2.632893
         33      1        6.320000          1.420110
         34      1        5.080000          1.669993
         35      1        6.500000          2.420185
         36      1        5.600000          1.179645
         37      1        5.400000          0.252575
         38      1        8.300000          0.424086
         39      1       10.000000          1.356537

   Bus Voltages and Phase Angles

   Bus Number      Phase Angle      Voltage Magnitude
          1        -12.485636             1.045246
          2        -10.217808             1.042309
          3        -13.174062             1.014866
          4        -13.203740             0.986992
          5        -11.514228             0.986908
          6        -10.694206             0.990154
          7        -13.041608             0.974735
          8        -13.604321             0.973080
          9        -13.791826             1.018698
         10         -8.505794             1.004618
         11         -9.253588             0.998516
         12         -9.337947             0.986096
         13         -9.313809             1.001089
         14        -11.229626             0.997346
         15        -12.052931             1.003353
         16        -10.784295             1.020845
         17        -12.202674             1.017563
         18        -13.452860             1.008661
         19         -5.541419             1.044968
         20         -6.522538             0.986749
         21         -8.344852             1.024066
         22         -3.856379             1.045675
         23         -4.055999             1.040524
         24        -10.664925             1.027350
         25         -8.915253             1.051848
         26        -10.252603             1.043502
         27        -12.322836             1.025594
         28         -6.715325             1.045685
         29         -3.942667             1.046898
         30         -7.783109             1.047500
         31          0.000000             0.982000
         32         -0.409294             0.983100
         33         -0.312736             0.997200
         34         -1.270213             1.012300
         35          1.124969             1.049300
         36          3.824890             1.063500
         37         -2.101837             1.027800
         38          3.132727             1.026500
         39        -13.828199             1.030000
        504        -14.091179             0.981248
        507        -13.466141             0.971168
        508        -14.559654             0.965231
        518        -13.729509             1.005289
Missing generators on at least one processor
Monitoring generators:
  Bus:       32 Generator ID: 1 
Generator Watch Frequency: 1
Vector has no data in GlobalVector::upload on process 0
MA error: MA_init: MA already initialized
Failure: RuntimeError (Vector has no data in GlobalVector::upload on process 0
) ... ERROR
hadrec_test (tests.gridpack_test.GridPACKTester) ... ok
hello_test (tests.gridpack_test.GridPACKTester) ... ok
task_test (tests.gridpack_test.GridPACKTester) ... ok

======================================================================
ERROR: Failure: RuntimeError (Vector has no data in GlobalVector::upload on process 0
)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lei/Install_package/GridPACK-renke/python/.eggs/nose-1.3.7-py3.7.egg/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/lei/Install_package/GridPACK-renke/python/.eggs/nose-1.3.7-py3.7.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/lei/Install_package/GridPACK-renke/python/.eggs/nose-1.3.7-py3.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/lei/Install_package/GridPACK-renke/python/.eggs/nose-1.3.7-py3.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/lei/anaconda3/envs/helics-example/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/lei/anaconda3/envs/helics-example/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lei/Install_package/GridPACK-renke/python/src/tests/39bus_test_example.py", line 78, in <module>
    hadapp.initializeDynSimu(busfaultlist, 0) # 0 inidcates read in the first dyr dynamic parameter file, the xml file supports multiple dyr files read in
RuntimeError: Vector has no data in GlobalVector::upload on process 0


----------------------------------------------------------------------
Ran 4 tests in 25.297s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=4 errors=1 failures=0>
��������������������0����0����0����0����0����0����error: Test failed: <unittest.runner.TextTestResult run=4 errors=1 failures=0>
Segmentation fault (core dumped)
```

**Comment by lzheng28** [comment]
I delete the three files (_39bus_scatterload_steptest_new_itr.py 39bus_test_example.py 39bus_test_pfdata.py_) in src/tests because I think in the README.md, there are only three tests, and I can run _hadrec.py input_tamu500_step005.xml_, but when I run ```python 39bus_test_example.py input_39bus_step005_v33.xml```, it shows that python can't find the module gridpack.
```
(helics-example) lei@lei-VirtualBox:~/Install_package/GridPACK-renke/python/src/tests$ python 39bus_test_example.py input_39bus_step005_v33.xml 
Traceback (most recent call last):
  File "39bus_test_example.py", line 13, in <module>
    import gridpack
ModuleNotFoundError: No module named 'gridpack'
```
How could I solve this problem? Is there anything wrong when I run this example? Thank you so much!

**Comment by lzheng28** [comment]
I found that I need to put this file ```gridpack.cpython-37m-x86_64-linux-gnu.so``` into the folder when I need to use ```import gridpack```

**Comment by huangrenke** [comment]
If the gridpack python wrapper installed correctly, you should be able to import gridpack in your python.

You do not need to run the test procedure. The reason you need to put "gridpack.cpython-37m-x86_64-linux-gnu.so" in your test folder is because you only build it but have not installed it. Follow the following steps to install gridpack python wrapper:

GRIDPACK_DIR=/where/your/gridpack/install/folder/is
export GRIDPACK_DIR
RHEL_OPENMPI_HACK=yes
export RHEL_OPENMPI_HACK
python setup.py build
python setup.py install

After that, you should be able to import gridpack module in your python.

and then you can just run the two examples I mentioned by

python 39bus_test_example.py
python 39bus_scatterload_steptest_new_itr.py

**Comment by lzheng28** [comment]
Oh, thank you so much, I think it's because I create an virtual environment but forget to activate it when I run it. And now I can run them successfully without the .so file.

And I still have two questions.
First, I find that dynamic simulation source codes has been changed in branch features/hadrec, and we can run dynamic simulation step by step in dsf_main.cpp, does this mean we can change the Load of specific bus in dsf_main.cpp and get correct result? Because I think for each time step, the Y matrix would be updated according to current status when it calls gridpack::dynamic_simulation::DSFullApp::executeOneSimuStep() function.

Second, is there an README.md or introduction for hadrec_main.cpp? I'm interested in what the hadrec_main.cpp do.

**Comment by lzheng28** [comment]
Oh, thank you so much, I think it's because I create an virtual environment but forget to activate it when I run it. And now I can run them successfully without the .so file.

And I still have two questions.
First, I find that dynamic simulation source codes has been changed in branch features/hadrec, and we can run dynamic simulation step by step in dsf_main.cpp, does this mean we can change the Load of specific bus in dsf_main.cpp and get correct result? Because I think for each time step, the Y matrix would be updated according to current status when it calls gridpack::dynamic_simulation::DSFullApp::executeOneSimuStep() function. I tried this method, but the result doesn't change. 
And I find that using the GridPACK C++ source codes will help me debug, sometimes GridPACK wrapper only gives me a error like
```
Traceback (most recent call last):
  File "9bus_test.py", line 125, in <module>
    hadapp.executeDynSimuOneStep() # execute one time step dynamic simulation
RuntimeError: 0: PETSc KSP diverged after 0 iterations, reason: -9
Segmentation fault (core dumped)
```

Second, is there an README.md or introduction for hadrec_main.cpp? I'm interested in what the hadrec_main.cpp do.

**Comment by lzheng28** [comment]
Oh, thank you so much, I think it's because I create an virtual environment but forget to activate it when I run it. And now I can run them successfully without the .so file.

And I still have two questions.
First, I find that dynamic simulation source codes has been changed in branch features/hadrec, and we can run dynamic simulation step by step in dsf_main.cpp, does this mean we can change the Load of specific bus in dsf_main.cpp and get correct result? Because I think for each time step, the Y matrix would be updated according to current status when it calls ```gridpack::dynamic_simulation::DSFullApp::executeOneSimuStep()``` function. I tried this method, and I call ```gridpack::dynamic_simulation::DSFullApp::applyConstYLoad_Change_P()``` and ```gridpack::dynamic_simulation::DSFullApp::applyConstYLoad_Change_Q()``` function to revise P and Q of the specific bus, and find the result changed, but I don't know if it's correct to do so. Or should I use ```scatterInjectionLoadNew()``` function to set new Load? But I found it has error when I do so.
And I find that using the GridPACK C++ source codes will help me debug, sometimes GridPACK wrapper only gives me an error like
```
Traceback (most recent call last):
  File "9bus_test.py", line 125, in <module>
    hadapp.executeDynSimuOneStep() # execute one time step dynamic simulation
RuntimeError: 0: PETSc KSP diverged after 0 iterations, reason: -9
Segmentation fault (core dumped)
```

**Comment by lzheng28** [comment]
I read the ```hadrec.cpp``` and find that it uses ```DSFullApp::applyConstYLoad_Change_P()``` and ```DSFullApp::applyConstYLoad_Change_Q()``` function to change the Load, so is it equivalent to the ```scatterInjectionLoadNew() ``` function which is used in ```39bus_scatterload_steptest_new_itr()```?

**Comment by lzheng28** [comment]
I revised parameters in ```input_39bus_step005_v33.xml``` from 
```
    <simulationTime>45.0</simulationTime>
    <timeStep>0.005</timeStep>
    <faultEvents>
      <faultEvent>
        <beginFault> 111.0</beginFault>
        <endFault>   111.08</endFault>
        <faultBranch>4  5</faultBranch>
        <timeStep>   0.005</timeStep>
      </faultEvent>
    </faultEvents>
```
to
```
    <simulationTime>60.0</simulationTime>
    <timeStep>0.005</timeStep>
    <faultEvents>
      <faultEvent>
        <beginFault> 30.0</beginFault>
        <endFault>   30.08</endFault>
        <faultBranch>4  5</faultBranch>
        <timeStep>   0.005</timeStep>
      </faultEvent>
    </faultEvents>
``` 
And delete codes related to the bus fault, line tripping, load shedding, generator tripping in ```39bus_test_example.py``` (The reason why I do that is that I want to test how the 39bus power system acts when there is only an branch fault), but I find that the result of observed elements would be static which means they don't change. This is strange because I think the system would change when there is a branch fault when the time is 30. Is that right?
