### ISSUE TITLE
Is Ubuntu 20.04 LTS supported?

### ISSUE THREAD

**Issue by temcdrm** [GridOPTICS/GridPACK#86]
Trying to work around this issue, https://github.com/GlobalArrays/ga/issues/235, I was unable to install the pre-built version of GridPACK:
```
tom@uvm:~/src/ga$ sudo add-apt-repository ppa:wperkins/gridpack-ppa
Cannot add PPA: 'ppa:~wperkins/ubuntu/gridpack-ppa'.
ERROR: '~wperkins' user or team does not exist.
```
This worked when I had Ubuntu 18.04 LTS.  Is the newer version not supported?

**Comment by wperkins** [comment]
@temcdrm Sorry, we don't have binaries for Ubuntu 20.  The PETSc version on Ubuntu 20 is too new for GridPACK (3.12).  We are in search of funding to bring GridPACK up to date with PETSc and Ubuntu, and hoping to have some early next year.  Until then, I can only suggest building from source.  You should be able to install Boost MPI (as with Ubuntu 18) and get an appropriate compiler.  You'll have to build PETSc (<= 3.10). You can build an appropriately configured Global Arrays with GridPACK by using `-D BUILD_GA:BOOL=TRUE` when configuring GridPACK with CMake.   You'll find some examples of how to build PETSc for GridPACK [here](https://www.gridpack.org/wiki/index.php/How_to_Build_GridPACK), under CentOS.

**Comment by temcdrm** [comment]
Thanks for the advice.  I ended up making another small VM with Ubuntu 18 LTS, just for GridPACK, and that works for what I need.

Having followed these instructions yesterday, https://www.gridpack.org/wiki/index.php/Building_on_Ubuntu_18, I already had the too-new PETSc on Ubuntu 20, and didn't want to undo it.

**Comment by wperkins** [comment]
I think this is resolved. I really can't keep up with PPA releases.  I'll look into deleting them.
