### ISSUE TITLE
MacOS Circular Shared Library Dependency

### ISSUE THREAD

**Issue by wperkins** [GridOPTICS/GridPACK#90]
I am unable to build GridPACK as shared libraries on my Mac. I can build static libraries fine, but not shared.  I get an error like this trying to build the `gridpack_math` library:
```
Undefined symbols for architecture x86_64:
  "gridpack::NoPrint::status()", referenced from:
      gridpack::math::Initialize(int*, char***) in petsc_math.cpp.o
      gridpack::math::PETScLinearSolverImplementation<std::__1::complex<double>, int>::PETScLinearSolverImplementation(gridpack::math::MatrixT<std::__1::complex<double>, int>&) in petsc_linear_solver.cpp.o
      gridpack::math::PETScLinearSolverImplementation<double, int>::PETScLinearSolverImplementation(gridpack::math::MatrixT<double, int>&) in petsc_linear_solver.cpp.o
  "gridpack::NoPrint::instance()", referenced from:
      gridpack::math::Initialize(int*, char***) in petsc_math.cpp.o
      gridpack::math::PETScLinearSolverImplementation<std::__1::complex<double>, int>::PETScLinearSolverImplementation(gridpack::math::MatrixT<std::__1::complex<double>, int>&) in petsc_linear_solver.cpp.o
      gridpack::math::PETScLinearSolverImplementation<double, int>::PETScLinearSolverImplementation(gridpack::math::MatrixT<double, int>&) in petsc_linear_solver.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [math/libgridpack_math.3.3.dylib] Error 1
make[1]: *** [math/CMakeFiles/gridpack_math.dir/all] Error 2
make: *** [all] Error 2
```
The `NoPrint` singleton is built into the `gridpack_environment` library which depends on the math library.  The `gridpack_environment` cannot be added as a `gridpack_math` dependency, since that generates a circular dependency error from CMake.  

This does not happen on any Linux system I've tried.

**Comment by wperkins** [comment]
I've mapped out individual library dependencies below.  The picture does not include several unnecessary links.
![library-graph dot](https://user-images.githubusercontent.com/8239636/193906647-14bc3090-e2b1-4206-849f-635661859d49.png)
I suggest moving the `NoPrint` to `configuration`.  `NoPrint` does not depend on `Evironment` or anything else and it is kind of a configuration parameter.  

Do you have thoughts @bjpalmer?

**Comment by bjpalmer** [comment]
I guess configuration is probably the way to go. The other possibility is to stick it in its own library, but apart from the fact that NoPrint is really small, we'd have to fix up a ton of CMakeLists.txt files.
