### ISSUE TITLE
Discussion: splitting input file lines

### ISSUE THREAD

**Issue by abhyshr** [GridOPTICS/GridPACK#96]
The splitting of a line read from a PSSE file into tokens is done using the `boost::algorithm::split` method. See the code [here]( https://github.com/GridOPTICS/GridPACK/blob/cdfa5e8ed839cb4bc7d2e3a0c8f8f75ee85e9f64/src/parser/base_pti_parser.hpp#L119). 

The function call done here is 
```
boost::algorithm::split(split_line, line, boost::algorithm::is_any_of(","),
                    boost::token_compress_off);
```

This code splits the string based of comma separator only. There is code used from utils to do additional work for doing additional clean up (rremove white spaces, handle space separated fields etc.)

To me it seems like the additional code can be avoided by modifying the spllit call above to pass in additional delimiters and using `token_compress_on`.

```
boost::algorithm::split(split_line, line, boost::algorithm::is_any_of(" ,\r\t"),
                    boost::token_compress_on);
```
 I think this should take care of splitting the line correctly (not tested yet). There won't be any additional code necessary I think. 

This change will not work for input lines like
```
30, 'xyz',1,,,,2,,, \
```
i.e., the lines that multiple commas together. I am not sure if anyone has come across data files with such format and/or whether we should support such cases.

Thoughts? @bjpalmer @chenyousu @wperkins

**Comment by bjpalmer** [comment]
We got a lot of requests to support the multiple comma format and where able get as far as supporting is format if the assumed value was zero. This seems to work in most instances. Personally, I think the multiple comma format is ghastly, but apparently it shows up in a lot of PSS/E raw files and it is a pain to keep converting them to actual values. My guess is that people will be upset if we get rid of this capability.

**Comment by wperkins** [comment]
It may not be palatable to the rest of the team, but I would recommend a parser generator, like [Boost::Spirit](https://www.boost.org/doc/libs/1_67_0/libs/spirit/doc/html/index.html).  The learning curve is pretty steep, but a much more robust and flexible and maintainable parser can be developed with a lot less code.  My experience is [Spirit.Classic](https://www.boost.org/doc/libs/1_67_0/libs/spirit/classic/index.html).  I can provide an example.
